### ISSUE TITLE
cannot load such file -- git-lfs-s3/authentication (LoadError)

### ISSUE THREAD

**Issue by 0xGuybrush** [meltingice/git-lfs-s3#2]
Trying to run the gem gives the error:

```
~/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- git-lfs-s3/authentication (LoadError)
    from ~/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ~/.rvm/gems/ruby-2.2.1/gems/git-lfs-s3-0.1.0/lib/git-lfs-s3.rb:6:in `<top (required)>'
    from ~/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ~/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ~/.rvm/gems/ruby-2.2.1/gems/git-lfs-s3-0.1.0/bin/git-lfs-s3:5:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.1/bin/git-lfs-s3:23:in `load'
    from ~/.rvm/gems/ruby-2.2.1/bin/git-lfs-s3:23:in `<main>'
    from ~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from ~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

It seems to be referencing an 'authentication' file that's not in the lib folder of the repo? (Disclaimer: I know no Ruby!)

I'm running this on OSX — v10.10.3. Let me know if you need more details.

**Comment by meltingice** [comment]
Whoa, not sure how that one slipped by! I've pushed a fixed version to Rubygems, give that a try.
